/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AtChar123handleChar125RouteImport } from './routes/@{$handle}'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OgHandleRouteImport } from './routes/og/$handle'

const AtChar123handleChar125Route = AtChar123handleChar125RouteImport.update({
  id: '/@{$handle}',
  path: '/@{$handle}',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OgHandleRoute = OgHandleRouteImport.update({
  id: '/og/$handle',
  path: '/og/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/og/$handle': typeof OgHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/og/$handle': typeof OgHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/@{$handle}': typeof AtChar123handleChar125Route
  '/og/$handle': typeof OgHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/@{$handle}' | '/og/$handle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/@{$handle}' | '/og/$handle'
  id: '__root__' | '/' | '/@{$handle}' | '/og/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtChar123handleChar125Route: typeof AtChar123handleChar125Route
  OgHandleRoute: typeof OgHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/@{$handle}': {
      id: '/@{$handle}'
      path: '/@{$handle}'
      fullPath: '/@{$handle}'
      preLoaderRoute: typeof AtChar123handleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$handle': {
      id: '/og/$handle'
      path: '/og/$handle'
      fullPath: '/og/$handle'
      preLoaderRoute: typeof OgHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtChar123handleChar125Route: AtChar123handleChar125Route,
  OgHandleRoute: OgHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
